[build]
  command = "pip install -r requirements.txt && python app.py"
  publish = "templates"

[build.environment]
  PYTHON_VERSION = "3.10.12"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
